from sys import exit


def handle_error(message):
    print(f"Error: {message}")
    exit(1)
